# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=panel.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cells', models.CharField(choices=[('T Cell', 'T Cell'), ('Dentritic Cell', 'Dendritic Cell'), ('B Cell', 'B Cell')], max_length=50)),
                ('markers', models.CharField(default=['CD2 (LFA-2)', 'CD3', 'CD4', 'CD5', 'CD7', 'CD8', 'CD45 (Leucocyte Common Antigen)'], max_length=120)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
