# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='content',
            new_name='Description',
        ),
    ]
