# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panel',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 6, 22, 15, 9, 39, 890527, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
