# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20160313_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='markers',
            field=models.CharField(choices=[('CD3', 'CD3'), ('CD4', 'CD4'), ('CD8', 'CD8'), ('CD45', 'CD45 Leukocyte Common Antigen')], default=('CD3', 'CD3'), max_length=9),
            preserve_default=False,
        ),
    ]
