# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20160622_1509'),
        ('panel', '0003_auto_20160621_2020'),
    ]

    operations = [
    ]
