# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_panel_markers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='markers',
        ),
    ]
