# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_panel_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='markers',
            field=models.CharField(choices=[('CD2', 'CD2 (LFA-2)'), ('CD3', 'CD3'), ('CD4', 'CD4'), ('CD5', 'CD5'), ('CD7', 'CD7'), ('CD8', 'CD8'), ('CD3', 'CD45 (Leucocyte Common Antigen)')], max_length=9),
        ),
    ]
