# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='SignUp',
        ),
    ]
