# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20160313_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='markers',
        ),
        migrations.AddField(
            model_name='panel',
            name='cells',
            field=models.CharField(choices=[('T Cell', 'T Cell'), ('Dentritic Cell', 'Dendritic Cell')], default=datetime.datetime(2016, 3, 15, 0, 54, 14, 261892, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
