# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20160314_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='cells',
            field=models.CharField(choices=[('T Cell', 'T Cell'), ('Dentritic Cell', 'Dendritic Cell')], default='T Cell', max_length=50),
        ),
    ]
