# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20160314_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='markers',
            field=models.TextField(default=datetime.datetime(2016, 3, 15, 1, 7, 45, 459704, tzinfo=utc), verbose_name=()),
            preserve_default=False,
        ),
    ]
