# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_panel_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='markers',
            field=models.CharField(default=['CD2 (LFA-2)', 'CD3', 'CD4', 'CD5', 'CD7', 'CD8', 'CD45 (Leucocyte Common Antigen)'], max_length=120),
        ),
    ]
