# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20160319_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='Description',
            new_name='description',
        ),
    ]
