# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20160503_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='panel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
