# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20160612_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panel',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panel',
            name='cells',
            field=models.CharField(choices=[('T Cell', 'T Cell'), ('Dentritic Cell', 'Dendritic Cell'), ('B Cell', 'B Cell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
