# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20160612_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=panel.models.upload_location, width_field='width_field'),
        ),
    ]
